[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PYTHON_VERSION = "3.12"
